services:
  - type: web
    name: rocketgpt-core-api
    runtime: python
    plan: free
    rootDir: apps/core-api
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server_stub_fastapi:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
