name: Feature Spec
description: Define business logic for AI codegen
labels: ["approved-for-codegen"]
body:
  - type: input
    id: title
    attributes: { label: Title, placeholder: "M2 — Self-Apply E2E" }
  - type: textarea
    id: context
    attributes: { label: Context, description: "Background/context" }
  - type: textarea
    id: requirements
    attributes: { label: Business Requirements, description: "Numbered points" }
  - type: textarea
    id: targets
    attributes: { label: Target Files (path + purpose), description: "List files to create/modify" }
  - type: textarea
    id: acceptance
    attributes: { label: Acceptance Criteria, description: "What proves it works?" }
