"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CognitiveSignalType = void 0;
var CognitiveSignalType;
(function (CognitiveSignalType) {
    CognitiveSignalType["TASK_STARTED"] = "TASK_STARTED";
    CognitiveSignalType["TASK_COMPLETED"] = "TASK_COMPLETED";
    CognitiveSignalType["TASK_FAILED"] = "TASK_FAILED";
    CognitiveSignalType["WORKFLOW_STEP_ENTERED"] = "WORKFLOW_STEP_ENTERED";
    CognitiveSignalType["WORKFLOW_STEP_EXITED"] = "WORKFLOW_STEP_EXITED";
    CognitiveSignalType["INSIGHT_DISCOVERED"] = "INSIGHT_DISCOVERED";
    CognitiveSignalType["PATTERN_DETECTED"] = "PATTERN_DETECTED";
    CognitiveSignalType["NEW_KNOWLEDGE_STORED"] = "NEW_KNOWLEDGE_STORED";
    CognitiveSignalType["CONFIDENCE_HIGH"] = "CONFIDENCE_HIGH";
    CognitiveSignalType["CONFIDENCE_LOW"] = "CONFIDENCE_LOW";
    CognitiveSignalType["UNCERTAINTY_RAISED"] = "UNCERTAINTY_RAISED";
    CognitiveSignalType["AMBIGUITY_DETECTED"] = "AMBIGUITY_DETECTED";
    CognitiveSignalType["ANOMALY_DETECTED"] = "ANOMALY_DETECTED";
    CognitiveSignalType["LOGIC_CONFLICT"] = "LOGIC_CONFLICT";
    CognitiveSignalType["MODEL_DRIFT"] = "MODEL_DRIFT";
    CognitiveSignalType["CATS_FAILURE_PATTERN"] = "CATS_FAILURE_PATTERN";
    CognitiveSignalType["REASONING_REQUIRED"] = "REASONING_REQUIRED";
    CognitiveSignalType["REPLAN_REQUIRED"] = "REPLAN_REQUIRED";
    CognitiveSignalType["MEMORY_LOOKUP_REQUIRED"] = "MEMORY_LOOKUP_REQUIRED";
    CognitiveSignalType["AGENT_COLLABORATION_REQUIRED"] = "AGENT_COLLABORATION_REQUIRED";
    CognitiveSignalType["ATTENTION_REQUESTED"] = "ATTENTION_REQUESTED";
    CognitiveSignalType["ATTENTION_ESCALATED"] = "ATTENTION_ESCALATED";
    CognitiveSignalType["PRIORITY_RECALCULATED"] = "PRIORITY_RECALCULATED";
})(CognitiveSignalType || (exports.CognitiveSignalType = CognitiveSignalType = {}));
