name: self-redevelopment
on:
  schedule: [{ cron: '0 2 * * *' }] # daily 02:00 UTC
  workflow_dispatch: {}
jobs:
  refactor:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      - name: Auto-fix UI (eslint/format)
        working-directory: rocketgpt_v3_full/webapp/next
        run: |
          npm i
          npx eslint . --ext .ts,.tsx --fix || true
          npx prettier -w . || true

      - name: Auto-fix core-api (ruff)
        run: |
          pipx install ruff
          ruff check rocketgpt_v3_full/apps/core-api --fix || true
          ruff format rocketgpt_v3_full/apps/core-api || true

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: chore/auto-refactor
          title: 'chore: automated refactor & lint/format'
          commit-message: 'chore: automated refactor & lint/format'
          body: |
            Automated refactor: ESLint/Prettier/ruff. Safe, mechanical changes only.
          labels: chore, automation
